name: Auto merge pull requests

on:
  pull_request:
    types:
      - labeled
      - unlabeled
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

  status: {}

jobs:
  autosquash-skip:

    name: Auto squash (CI skip)
    runs-on: ubuntu-latest

    if: github.event.pull_request.head.repo.full_name == 'ybw0014/guizhan-builds'

    steps:
    - name: Auto squash
      uses: pascalgn/automerge-action@v0.15.6
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        UPDATE_RETRIES: 0
        MERGE_METHOD: squash
        MERGE_FORKS: false
        MERGE_DELETE_BRANCH: true
        MERGE_LABELS: 'merge/skip'
        MERGE_COMMIT_MESSAGE: '[CI skip] ${{ github.event.pull_request.title }}'
        
  autosquash-normal:

    name: Auto squash (Normal)
    runs-on: ubuntu-latest

    if: github.event.pull_request.head.repo.full_name == 'ybw0014/guizhan-builds'

    steps:
    - name: Auto squash
      uses: pascalgn/automerge-action@v0.15.6
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        UPDATE_RETRIES: 0
        MERGE_METHOD: squash
        MERGE_FORKS: false
        MERGE_DELETE_BRANCH: true
        MERGE_LABELS: 'merge/normal'
        MERGE_COMMIT_MESSAGE: '${{ github.event.pull_request.title }}'
